name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:latest
        ports:
          - 27017:27017

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: 建立Node.js环境
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: 安装后端依赖
        working-directory: ./backend
        run: npm install

      - name: 安装前端依赖
        working-directory: ./frontend
        run: npm install

      - name: 载入环境变量
        run: |
          if [ -f .env ]; then
            echo "Loading environment variables from .env file"
            cat .env | grep -v '^#' >> $GITHUB_ENV
          fi

      - name: 等待数据库准备
        run: |
          echo "Waiting for MongoDB to be ready..."
          for i in {1..30}; do
            nc -zv localhost 27017 && echo "MongoDB is ready" && break
            echo "Waiting for MongoDB..."
            sleep 1
          done

      - name: 执行后端测试
        working-directory: ./backend
        run: npm test

      - name: 软件构建
        working-directory: ./backend
        run: npm run build

      - name: 清除开发依赖
        run: npm prune --omit=dev